import { Box } from '@components';
import {
  // AccordionDemo,
  // AlertDemo,
  // AppBarDemo,
  // AutcompleteDemo,
  // AvatarDemo,
  // BackdropDemo,
  // BadgeDemo,
  // BottomNavigationDemo,
  // BoxDemo,
  // BreadcrumbsDemo,
  // ButtonDemo,
  // ButtonGroupDemo,
  // CardDemo,
  // CheckboxDemo,
  // ChipDemo,
  // ClickAwayListenerDemo,
  // ContainerDemo,
  // DialogDemo,
  // DividerDemo,
  DrawerDemo // FabDemo,
  // FocusTrapDemo,
  // FormControlDemo,
  // GridDemo,
  // InputDemo,
  // LinkDemo,
  // ListDemo,
  // MenuDemo,
  // ModalDemo,
  // MultiSelectDemo,
  // NoSsrDemo,
  // PaginationDemo,
  // PaperDemo,
  // PopoverDemo,
  // PopperDemo,
  // ProgressDemo,
  // RadioDemo,
  // SelectDemo,
  // SliderDemo,
  // SkeletonDemo,
  // SnackbarDemo,
  // SwitchDemo,
  // TabDemo,
  // TableDemo,
  // TextDemo,
  // TextareaAutosizeDemo,
  // TextFieldDemo,
  // ToggleButtonDemo,
  // TooltipDemo
} from '@views';

const App = () => {
  return <DrawerDemo />;
};

export default App;
